blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/PhDLeToanThang/automation/terraform-provider-vra/discussions
    about: Having trouble working with the provider? Join the discussions to ask and answer questions in the community.